apiVersion: apps/v1
kind: Deployment
metadata:
  name: techtrends
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: techtrends
  template:
    metadata:
      labels:
        app: techtrends
    spec:
      containers:
      - name: techtrends
        image: yotaponta/dockertest:techtrends:latest
        ports:
        - containerPort: {{ .Values.containerPort }}
        resources:
          requests:
            memory: "{{ .Values.resources.requests.memory }}"
            cpu: "{{ .Values.resources.requests.cpu }}"
          limits:
            memory: "{{ .Values.resources.limits.memory }}"
            cpu: "{{ .Values.resources.limits.cpu }}"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 3111
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /healthz
            port: 3111
          initialDelaySeconds: 5
          periodSeconds: 5


## image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
##        imagePullPolicy: {{ .Values.image.pullPolicy }}

##            path: {{ .Values.livenessProbe.path }}
##            port: {{ .Values.livenessProbe.port }}
##            path: {{ .Values.readinessProbe.path }}
##            port: {{ .Values.readinessProbe.port }}
