namespace: staging

image:
  repository: 'https://github.com/yotaponta/nd064_course_1'
  tag: latest
  
service:
  port: 5111

replicaCount: 3

resources:
  requests:
    memory: "90Mi"
    cpu: "300m"
  limits:
    memory: "128Mi"
    cpu: "500m"
