name: TechTrends - Package with Docker

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.7,3.8]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push to DockerHub
        uses: docker/build-push-action@v2
        with:
          context: .
          file: /Users/a5014094/nd064_course_1/project/Dockerfile 
          platforms: linux/amd64
          push: true
          tags: |
            yotaponta/techtrends:latest
          dockerfile: /Users/a5014094/nd064_course_1/project/Dockerfile
          python-version: ${{matrix.python-version}}
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
          
