name: TechTrends - Package with Docker

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    #- name: Build Docker image
    #  run: docker build -t techtrends:latest -f ./project/Dockerfile .

    #- name: Push Docker image to Docker Hub
    #  run: docker push yotaponta/dockertest:techtrends

    - name: Build and push Docker image
      uses: docker/build-push-action@v3
      with:
        context: ./project/
        file: ./project/Dockerfile
        push: true
        tags: yotaponta/dockertest:latest
